### ISSUE TITLE
Support for compressToEncodedURIComponent and decompressFromEncodedURIComponent.

### ISSUE THREAD

**Issue by HandsTest** [rufushuang/lz-string4java#2]
Can you import these latest methods in the lib. 

Thanks

**Comment by rufushuang** [comment]
is it a very little step from base64 to endodedURI? just such as string replace?

ok. while the original lz-string has updated version, i will give it a try to port the latest version.
in several days, maybe

**Comment by rufushuang** [comment]
Due to the compressToBase64 changed some from version 1.3.3(the version I port) to version 1.4.4(the version latest provide URIComponent series). So the compressed result is not just the same, some tail characters as AAA== added. endodedURI is just the same.

The tail characters does affect Base64/EncodedURIComponent decompress. I must spend more time on this.

**Comment by rufushuang** [comment]
DONE porting from 1.4.4,  URIComponent series supported.
But found version incompatible, see README.md.

Have a try!
